"""
报告生成服务
"""

import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors


class ReportGenerator:
    """PDF 报告生成器"""
    
    @staticmethod
    def generate_carbon_inventory_report(
        org_name: str,
        year: int,
        summary: dict
    ) -> bytes:
        """生成碳盘查报告 PDF"""
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        
        # 标题
        c.setFont("Helvetica-Bold", 24)
        c.drawString(50, height - 50, "Carbon Inventory Report")
        
        # 基本信息
        c.setFont("Helvetica", 12)
        c.drawString(50, height - 100, f"Organization: {org_name}")
        c.drawString(50, height - 120, f"Year: {year}")
        c.drawString(50, height - 140, f"Generated: {datetime.now().strftime('%Y-%m-%d')}")
        
        # 排放汇总
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 180, "Emission Summary (tCO2e)")
        
        c.setFont("Helvetica", 12)
        y = height - 210
        
        c.drawString(50, y, "Scope 1 (Direct):")
        c.drawRightString(300, y, f"{summary.get('scope_1', 0):.2f}")
        
        y -= 25
        c.drawString(50, y, "Scope 2 (Energy Indirect):")
        c.drawRightString(300, y, f"{summary.get('scope_2', 0):.2f}")
        
        y -= 25
        c.drawString(50, y, "Scope 3 (Other Indirect):")
        c.drawRightString(300, y, f"{summary.get('scope_3', 0):.2f}")
        
        y -= 40
        c.line(50, y + 15, 300, y + 15)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y, "Total Emissions:")
        c.drawRightString(300, y, f"{summary.get('total', 0):.2f}")
        
        # 底部声明
        c.setFont("Helvetica-Oblique", 10)
        c.setFillColor(colors.grey)
        c.drawString(50, 50, "Generated by CarbonOS SaaS Platform")
        
        c.showPage()
        c.save()
        
        buffer.seek(0)
        return buffer.getvalue()
