import { Agent } from '@/types';

/**
 * Shared mock agents store.
 * Both /api/agents and /api/agents/[id] routes import this single object,
 * ensuring data consistency across list and detail endpoints.
 */
export const mockAgents: Record<string, Agent[]> = {};

// Initialize with default dashboard data
mockAgents['dashboard_user'] = [
  {
    id: 'agent-001',
    name: 'CustomerBot',
    description: '智能客服 Agent，处理邮件和在线聊天支持请求，支持多语言',
    framework: 'LangChain',
    frameworkVersion: null,
    model: 'gpt-4-turbo',
    modelHash: null,
    configHash: null,
    toolManifestHash: null,
    status: 'active',
    userId: 'dashboard_user',
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-03-30T14:22:00Z',
    score: 92,
    evaluationCount: 12,
    passport: {
      status: 'valid',
      fingerprint: 'sha256:a3f8c1d2e4b5...7f9e',
      expiresAt: '2027-02-10T00:00:00Z',
    },
  },
  {
    id: 'agent-002',
    name: 'DataAnalyst Pro',
    description: '数据分析 Agent，自动生成报表、趋势分析和可视化图表',
    framework: 'CrewAI',
    frameworkVersion: null,
    model: 'claude-3-opus',
    modelHash: null,
    configHash: null,
    toolManifestHash: null,
    status: 'active',
    userId: 'dashboard_user',
    createdAt: '2026-01-15T10:30:00Z',
    updatedAt: '2026-03-29T09:15:00Z',
    score: 87,
    evaluationCount: 8,
    passport: {
      status: 'valid',
      fingerprint: 'sha256:b7e2f4a1c9d8...3e2a',
      expiresAt: '2027-01-15T00:00:00Z',
    },
  },
  {
    id: 'agent-003',
    name: 'SupportAgent',
    description: '技术支持 Agent，解答产品使用问题和故障排查',
    framework: 'OpenClaw',
    frameworkVersion: null,
    model: 'gpt-4o',
    modelHash: null,
    configHash: null,
    toolManifestHash: null,
    status: 'warning',
    userId: 'dashboard_user',
    createdAt: '2025-12-01T12:00:00Z',
    updatedAt: '2026-03-25T18:40:00Z',
    score: 71,
    evaluationCount: 15,
    passport: {
      status: 'expiring',
      fingerprint: 'sha256:c5d9e8b2a7f1...9d4c',
      expiresAt: '2026-04-15T00:00:00Z',
    },
  },
  {
    id: 'agent-004',
    name: 'CodeReviewer',
    description: '代码审查 Agent，自动检测安全漏洞和代码质量问题',
    framework: 'LangChain',
    frameworkVersion: null,
    model: 'claude-3-sonnet',
    modelHash: null,
    configHash: null,
    toolManifestHash: null,
    status: 'active',
    userId: 'dashboard_user',
    createdAt: '2026-03-01T06:00:00Z',
    updatedAt: '2026-03-31T02:10:00Z',
    score: 95,
    evaluationCount: 5,
    passport: {
      status: 'valid',
      fingerprint: 'sha256:d1a3b7c5e9f2...6b8e',
      expiresAt: '2027-03-01T00:00:00Z',
    },
  },
  {
    id: 'agent-005',
    name: 'SalesBot',
    description: '销售助手 Agent，处理询价、报价和客户跟进',
    framework: 'Custom',
    frameworkVersion: null,
    model: 'gpt-4',
    modelHash: null,
    configHash: null,
    toolManifestHash: null,
    status: 'inactive',
    userId: 'dashboard_user',
    createdAt: '2025-11-20T09:00:00Z',
    updatedAt: '2026-02-15T11:30:00Z',
    score: 58,
    evaluationCount: 3,
    passport: {
      status: 'expired',
      fingerprint: 'sha256:e2f4a8c6b1d3...4a7f',
      expiresAt: '2026-02-20T00:00:00Z',
    },
  },
  {
    id: 'agent-006',
    name: 'AuditLogger',
    description: '审计日志 Agent，负责记录和分析系统操作日志',
    framework: 'LangChain',
    frameworkVersion: null,
    model: 'gpt-4-turbo',
    modelHash: null,
    configHash: null,
    toolManifestHash: null,
    status: 'restricted',
    userId: 'dashboard_user',
    createdAt: '2025-10-05T08:00:00Z',
    updatedAt: '2026-03-20T16:30:00Z',
    score: 45,
    evaluationCount: 7,
    passport: {
      status: 'valid',
      fingerprint: 'sha256:f1a2b3c4d5e6...7g8h',
      expiresAt: '2026-10-05T00:00:00Z',
    },
  },
  {
    id: 'agent-007',
    name: 'ReportGen',
    description: '报告生成 Agent，自动生成各类业务报表',
    framework: 'CrewAI',
    frameworkVersion: null,
    model: 'claude-3-sonnet',
    modelHash: null,
    configHash: null,
    toolManifestHash: null,
    status: 'suspended',
    userId: 'dashboard_user',
    createdAt: '2025-09-15T14:00:00Z',
    updatedAt: '2026-03-15T09:00:00Z',
    score: 32,
    evaluationCount: 4,
    passport: {
      status: 'expired',
      fingerprint: 'sha256:h9i8j7k6l5m4...3n2o',
      expiresAt: '2026-03-10T00:00:00Z',
    },
  },
];

